services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: api-lexhub
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=db-lexhub
    ports:
      - "5432:5432"